# Form implementation generated from reading ui file '.\ui\chat.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../imgs/微信.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("QLabel{\n"
                                 "    background-color: #f4f4f4;\n"
                                 "}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
                                       "    background-color: #f4f4f4;\n"
                                       "}\n"
                                       "\n"
                                       "QScrollBar{\n"
                                       "    background-color: #f4f4f4;\n"
                                       "    width:8px\n"
                                       "}\n"
                                       "QScrollBar::sub-page,QScrollBar::add-page{\n"
                                       "    background-color: #f4f4f4;\n"
                                       "}\n"
                                       "QScrollBar::handle{\n"
                                       "    background-color:rgba(0,0,0,0.1);\n"
                                       "    border-radius:4px;\n"
                                       "}\n"
                                       "QScrollBar::handle:hover{\n"
                                       "    background-color:rgba(0,0,0,0.3);\n"
                                       "}\n"
                                       "QScrollBar::sub-line,QScrollBar::add-line{\n"
                                       "    border:none;\n"
                                       "}\n"
                                       "")
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setPlaceholderText("")
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
                                    "    background-color: #f4f4f4;\n"
                                    "}\n"
                                    "\n"
                                    "QScrollBar{\n"
                                    "    background-color: #f4f4f4;\n"
                                    "    width:8px\n"
                                    "}\n"
                                    "QScrollBar::sub-page,QScrollBar::add-page{\n"
                                    "    background-color: #f4f4f4;\n"
                                    "}\n"
                                    "QScrollBar::handle{\n"
                                    "    background-color:rgba(0,0,0,0.1);\n"
                                    "    border-radius:4px;\n"
                                    "}\n"
                                    "QScrollBar::handle:hover{\n"
                                    "    background-color:rgba(0,0,0,0.3);\n"
                                    "}\n"
                                    "QScrollBar::sub-line,QScrollBar::add-line{\n"
                                    "    border:none;\n"
                                    "}\n"
                                    "")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("QTextEdit{\n"
                                      "    background-color: #f4f4f4;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar{\n"
                                      "    background-color: #f4f4f4;\n"
                                      "    width:8px\n"
                                      "}\n"
                                      "QScrollBar::sub-page,QScrollBar::add-page{\n"
                                      "    background-color: #f4f4f4;\n"
                                      "}\n"
                                      "QScrollBar::handle{\n"
                                      "    background-color:rgba(0,0,0,0.1);\n"
                                      "    border-radius:4px;\n"
                                      "}\n"
                                      "QScrollBar::handle:hover{\n"
                                      "    background-color:rgba(0,0,0,0.3);\n"
                                      "}\n"
                                      "QScrollBar::sub-line,QScrollBar::add-line{\n"
                                      "    border:none;\n"
                                      "}\n"
                                      "")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listWidget = QtWidgets.QListWidget(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget{\n"
                                      "    background-color: #f4f4f4;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar{\n"
                                      "    background-color: #f4f4f4;\n"
                                      "    width:8px\n"
                                      "}\n"
                                      "QScrollBar::sub-page,QScrollBar::add-page{\n"
                                      "    background-color: #f4f4f4;\n"
                                      "}\n"
                                      "QScrollBar::handle{\n"
                                      "    background-color:rgba(0,0,0,0.1);\n"
                                      "    border-radius:4px;\n"
                                      "}\n"
                                      "QScrollBar::handle:hover{\n"
                                      "    background-color:rgba(0,0,0,0.3);\n"
                                      "}\n"
                                      "QScrollBar::sub-line,QScrollBar::add-line{\n"
                                      "    border:none;\n"
                                      "}\n"
                                      "")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(3, 3)
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "冷不丁聊天室"))
        self.label.setText(_translate("Form", "xxx进入了聊天室"))
        self.textBrowser.setHtml(_translate("Form",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "hr { height: 1px; border-width: 0; }\n"
                                            "li.unchecked::marker { content: \"\\2610\"; }\n"
                                            "li.checked::marker { content: \"\\2612\"; }\n"
                                            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dfgsd </p></body></html>"))
        self.textEdit.setHtml(_translate("Form",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "hr { height: 1px; border-width: 0; }\n"
                                         "li.unchecked::marker { content: \"\\2610\"; }\n"
                                         "li.checked::marker { content: \"\\2612\"; }\n"
                                         "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ghjfk </p></body></html>"))
        self.textEdit.setPlaceholderText(_translate("Form", "按 enter 发送消息、shift+enter 换行"))
        self.label_2.setText(_translate("Form", "群公告"))
        self.textEdit_2.setHtml(_translate("Form",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "hr { height: 1px; border-width: 0; }\n"
                                           "li.unchecked::marker { content: \"\\2610\"; }\n"
                                           "li.checked::marker { content: \"\\2612\"; }\n"
                                           "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ghjfk </p></body></html>"))
        self.label_3.setText(_translate("Form", "在线用户数：0"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "natsume"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "新建项目"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "新建项目"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "新建项目"))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
